/*
 * tests/test_tracker_fixtures.c - Validate tracker fixture tensors
 *
 * Loads SafeTensors fixture files generated by
 * scripts/gen_tracker_fixtures.py and asserts that each expected
 * reference tensor is present with a non-empty shape. The test is
 * gated behind the CMake option SAM3_FIXTURE_TESTS (default OFF) so
 * that builds without Python-generated fixtures are unaffected.
 * When the option is ON, a missing fixture is a hard failure.
 *
 * Once the C tracker pipeline produces backbone-conditioned outputs,
 * the shape checks below will be replaced with ASSERT_TENSOR_CLOSE
 * comparisons against the same reference tensors.
 *
 * Key types:  weight_reader
 * Depends on: test_helpers.h, core/weight.h, sam3/sam3.h, util/log.h
 * Used by:    CTest (only when SAM3_FIXTURE_TESTS=ON)
 *
 * Copyright (c) 2026 Rifky Bujana Bisri
 * SPDX-License-Identifier: MIT
 */

#include "test_helpers.h"

#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "sam3/sam3.h"
#include "core/weight.h"
#include "util/log.h"

#ifndef SAM3_SOURCE_DIR
#error "SAM3_SOURCE_DIR must be defined by CMake"
#endif

#define FIXTURE_DIR SAM3_SOURCE_DIR "/tests/fixtures/tracker"

/* --- Helpers  --- */

/*
 * load_fixture_tensor - Load a named tensor from a SafeTensors file.
 *
 * Returns malloc'd float data, or NULL on failure. Caller frees.
 * Populates out_n_dims, out_dims, out_nelems on success.
 */
static float *load_fixture_tensor(const char *path,
				  const char *tensor_name,
				  int *out_n_dims,
				  int *out_dims,
				  int *out_nelems)
{
	struct weight_reader r;
	struct weight_tensor_info info;
	float *data = NULL;
	int i, n, nelems;

	weight_reader_safetensors_init(&r);
	if (r.ops->open(&r, path) != SAM3_OK)
		return NULL;

	n = r.ops->n_tensors(&r);
	for (i = 0; i < n; i++) {
		if (r.ops->get_tensor_info(&r, i, &info) != SAM3_OK)
			continue;
		if (strcmp(info.name, tensor_name) != 0)
			continue;

		data = malloc(info.nbytes);
		if (!data)
			break;

		if (r.ops->read_tensor_data(&r, i, data, info.nbytes)
		    != SAM3_OK) {
			free(data);
			data = NULL;
			break;
		}

		if (out_n_dims)
			*out_n_dims = info.n_dims;
		if (out_dims)
			memcpy(out_dims, info.dims,
			       sizeof(int) * info.n_dims);
		if (out_nelems) {
			nelems = 1;
			for (int d = 0; d < info.n_dims; d++)
				nelems *= info.dims[d];
			*out_nelems = nelems;
		}
		break;
	}

	r.ops->close(&r);
	return data;
}

/*
 * require_fixture_tensor - Load a reference tensor or hard-fail.
 *
 * Wraps load_fixture_tensor so that a missing fixture is treated as
 * a hard test failure. Logs via sam3_log_error and aborts the test
 * process with exit(1) on any failure.
 */
static float *require_fixture_tensor(const char *path,
				     const char *tensor_name,
				     int *out_n_dims,
				     int *out_dims,
				     int *out_nelems)
{
	float *data = load_fixture_tensor(path, tensor_name, out_n_dims,
					  out_dims, out_nelems);
	if (!data) {
		sam3_log_error("fixture missing: %s (tensor '%s')",
			       path, tensor_name);
		sam3_log_error("run: python3 scripts/gen_tracker_fixtures.py");
		exit(1);
	}
	return data;
}

static void print_shape(const char *label, int n_dims, const int *dims)
{
	printf("  %s shape: [", label);
	for (int d = 0; d < n_dims; d++) {
		if (d > 0)
			printf(", ");
		printf("%d", dims[d]);
	}
	printf("]\n");
}

/* --- Test: memory attention fixture  --- */

static void test_tracker_memory_attn_fixture(void)
{
	float *data;
	int n_dims, dims[SAM3_MAX_DIMS], nelems;

	printf("test_tracker_memory_attn_fixture:\n");

	data = require_fixture_tensor(
		FIXTURE_DIR "/03_memory_attention/frame_0.safetensors",
		"output", &n_dims, dims, &nelems);

	ASSERT(n_dims > 0);
	ASSERT(nelems > 0);
	print_shape("memory_attn output", n_dims, dims);
	printf("  nelems: %d\n", nelems);

	free(data);
}

/* --- Test: mask decoder fixture  --- */

static void test_tracker_mask_decoder_fixture(void)
{
	float *mask_logits, *iou_scores;
	int ml_ndims, ml_dims[SAM3_MAX_DIMS], ml_nelems;
	int iou_ndims, iou_dims[SAM3_MAX_DIMS], iou_nelems;

	printf("\ntest_tracker_mask_decoder_fixture:\n");

	mask_logits = require_fixture_tensor(
		FIXTURE_DIR "/04_mask_decoder/frame_0.safetensors",
		"mask_logits", &ml_ndims, ml_dims, &ml_nelems);

	ASSERT(ml_ndims > 0);
	ASSERT(ml_nelems > 0);
	print_shape("mask_logits", ml_ndims, ml_dims);
	printf("  nelems: %d\n", ml_nelems);

	iou_scores = require_fixture_tensor(
		FIXTURE_DIR "/04_mask_decoder/frame_0.safetensors",
		"iou_scores", &iou_ndims, iou_dims, &iou_nelems);

	ASSERT(iou_ndims > 0);
	ASSERT(iou_nelems > 0);
	print_shape("iou_scores", iou_ndims, iou_dims);
	printf("  nelems: %d\n", iou_nelems);

	free(mask_logits);
	free(iou_scores);
}

/* --- Test: memory encoder fixture  --- */

static void test_tracker_memory_encoder_fixture(void)
{
	float *data;
	int n_dims, dims[SAM3_MAX_DIMS], nelems;

	printf("\ntest_tracker_memory_encoder_fixture:\n");

	data = require_fixture_tensor(
		FIXTURE_DIR "/05_memory_encoder/frame_0.safetensors",
		"output", &n_dims, dims, &nelems);

	ASSERT(n_dims > 0);
	ASSERT(nelems > 0);
	print_shape("memory_encoder output", n_dims, dims);
	printf("  nelems: %d\n", nelems);

	free(data);
}

/* --- Test: integration fixture (frame 0) --- */

static void test_tracker_integration_fixture(void)
{
	float *data;
	int n_dims, dims[SAM3_MAX_DIMS], nelems;

	printf("\ntest_tracker_integration_fixture:\n");

	data = require_fixture_tensor(
		FIXTURE_DIR "/07_integration/frame_0_masks.safetensors",
		"pred_masks", &n_dims, dims, &nelems);

	ASSERT(n_dims > 0);
	ASSERT(nelems > 0);
	print_shape("integration pred_masks (frame 0)", n_dims, dims);
	printf("  nelems: %d\n", nelems);

	free(data);
}

/* --- Test: propagation fixture (frame 1) --- */

static void test_tracker_propagation_fixture(void)
{
	float *data;
	int n_dims, dims[SAM3_MAX_DIMS], nelems;

	printf("\ntest_tracker_propagation_fixture:\n");

	data = require_fixture_tensor(
		FIXTURE_DIR "/07_integration/frame_1_masks.safetensors",
		"pred_masks", &n_dims, dims, &nelems);

	ASSERT(n_dims > 0);
	ASSERT(nelems > 0);
	print_shape("propagation pred_masks (frame 1)", n_dims, dims);
	printf("  nelems: %d\n", nelems);

	free(data);
}

/* --- Main  --- */

int main(void)
{
	if (access(FIXTURE_DIR "/metadata.json", F_OK) != 0) {
		sam3_log_error("tracker fixtures missing at %s",
			       FIXTURE_DIR);
		sam3_log_error("run: python3 scripts/gen_tracker_fixtures.py");
		return 1;
	}

	test_tracker_memory_attn_fixture();
	test_tracker_mask_decoder_fixture();
	test_tracker_memory_encoder_fixture();
	test_tracker_integration_fixture();
	test_tracker_propagation_fixture();

	TEST_REPORT();
}
