/*
 * tests/test_fixture_compare.c - Compare C outputs against Python fixtures
 *
 * Loads SafeTensors fixture files generated by tools/gen_fixtures.py
 * (from the reference Python SAM3 model) and compares them against
 * the C inference engine's outputs. Uses the Python fixture's exact
 * normalized image as input to isolate model differences from image
 * preprocessing differences.
 *
 * Skips gracefully if fixtures or model weights are not present.
 * Run gen_fixtures.py first to generate fixtures.
 *
 * Key types:  weight_reader (SafeTensors), sam3_processor
 * Depends on: test_helpers.h, sam3/sam3.h, core/weight.h,
 *             model/sam3_processor.h, model/graph_helpers.h
 * Used by:    CTest
 *
 * Copyright (c) 2026 Rifky Bujana Bisri
 * SPDX-License-Identifier: MIT
 */

#include "test_helpers.h"

#include <string.h>
#include <unistd.h>

#include "sam3/sam3.h"
#include "sam3/internal/processor_normalize.h"
#include "core/weight.h"
#include "model/sam3_processor.h"
#include "model/graph_helpers.h"

#ifndef SAM3_SOURCE_DIR
#error "SAM3_SOURCE_DIR must be defined by CMake"
#endif

#define FIXTURE_DIR SAM3_SOURCE_DIR "/tests/fixtures"
#define MODEL_PATH  SAM3_SOURCE_DIR "/models/sam3.sam3"

/* ── Helpers ───────────────────────────────────────────────────────── */

static int fixtures_available(void)
{
	return access(FIXTURE_DIR "/metadata.json", F_OK) == 0;
}

static int model_available(void)
{
	return access(MODEL_PATH, F_OK) == 0;
}

/*
 * load_fixture_tensor - Load a named tensor from a SafeTensors file.
 *
 * Returns malloc'd float data, or NULL on failure. Caller frees.
 * Populates out_n_dims, out_dims, out_nelems on success.
 */
static float *load_fixture_tensor(const char *path,
				  const char *tensor_name,
				  int *out_n_dims,
				  int *out_dims,
				  int *out_nelems)
{
	struct weight_reader r;
	struct weight_tensor_info info;
	float *data = NULL;
	int i, n, nelems;

	weight_reader_safetensors_init(&r);
	if (r.ops->open(&r, path) != SAM3_OK)
		return NULL;

	n = r.ops->n_tensors(&r);
	for (i = 0; i < n; i++) {
		if (r.ops->get_tensor_info(&r, i, &info) != SAM3_OK)
			continue;
		if (strcmp(info.name, tensor_name) != 0)
			continue;

		data = malloc(info.nbytes);
		if (!data)
			break;

		if (r.ops->read_tensor_data(&r, i, data, info.nbytes)
		    != SAM3_OK) {
			free(data);
			data = NULL;
			break;
		}

		if (out_n_dims)
			*out_n_dims = info.n_dims;
		if (out_dims)
			memcpy(out_dims, info.dims,
			       sizeof(int) * info.n_dims);
		if (out_nelems) {
			nelems = 1;
			for (int d = 0; d < info.n_dims; d++)
				nelems *= info.dims[d];
			*out_nelems = nelems;
		}
		break;
	}

	r.ops->close(&r);
	return data;
}

/*
 * compare_tensors - Compare two float arrays and report statistics.
 *
 * Returns the max absolute difference. Prints a summary line.
 */
static float compare_tensors(const char *label,
			     const float *actual,
			     const float *expected,
			     int nelems, float atol)
{
	float maxd = 0.0f;
	double sumd = 0.0;
	int n_exceed = 0;

	for (int i = 0; i < nelems; i++) {
		float d = (float)fabs((double)actual[i] -
				      (double)expected[i]);
		if (d > maxd)
			maxd = d;
		sumd += (double)d;
		if (d > atol)
			n_exceed++;
	}

	float meand = (float)(sumd / nelems);
	float pct_ok = 100.0f * (1.0f - (float)n_exceed / (float)nelems);

	printf("  %-30s max=%-10.4f mean=%-10.6f ok=%.1f%%\n",
	       label, (double)maxd, (double)meand, (double)pct_ok);

	return maxd;
}

/*
 * compare_nchw_fixture - Compare a cached [1,C,H,W] tensor
 * against a fixture SafeTensors file containing a "features" tensor.
 */
static float compare_nchw_fixture(const char *label,
				  const struct sam3_tensor *actual,
				  const char *fixture_path,
				  const char *tensor_name)
{
	int py_ndims, py_dims[SAM3_MAX_DIMS], py_nelems;
	float *py_data;
	float maxd;

	py_data = load_fixture_tensor(fixture_path, tensor_name,
				      &py_ndims, py_dims, &py_nelems);
	if (!py_data) {
		printf("  %-30s SKIP (fixture not loaded)\n", label);
		return -1.0f;
	}

	/* Verify shapes match (ignoring batch dim) */
	int c_nelems = 1;
	for (int d = 0; d < actual->n_dims; d++)
		c_nelems *= actual->dims[d];

	if (c_nelems != py_nelems) {
		printf("  %-30s SKIP (shape mismatch: C=%d vs Py=%d)\n",
		       label, c_nelems, py_nelems);
		free(py_data);
		return -1.0f;
	}

	maxd = compare_tensors(label, (const float *)actual->data,
			       py_data, py_nelems, 0.01f);
	free(py_data);
	return maxd;
}

/*
 * load_bin_file - Load raw float32 binary file from disk.
 *
 * Returns malloc'd float data, or NULL on failure. Caller frees.
 * Populates out_nelems with the number of floats read.
 */
static float *load_bin_file(const char *path, int *out_nelems)
{
	FILE *fp;
	long nbytes;
	float *data;

	fp = fopen(path, "rb");
	if (!fp)
		return NULL;

	fseek(fp, 0, SEEK_END);
	nbytes = ftell(fp);
	fseek(fp, 0, SEEK_SET);

	if (nbytes <= 0 || nbytes % sizeof(float) != 0) {
		fclose(fp);
		return NULL;
	}

	data = malloc((size_t)nbytes);
	if (!data) {
		fclose(fp);
		return NULL;
	}

	if (fread(data, 1, (size_t)nbytes, fp) != (size_t)nbytes) {
		free(data);
		fclose(fp);
		return NULL;
	}

	fclose(fp);
	if (out_nelems)
		*out_nelems = (int)(nbytes / sizeof(float));
	return data;
}

/*
 * compare_bin_vs_fixture - Compare a /tmp/dbg_*.bin dump against a
 * SafeTensors fixture tensor.
 *
 * Compares first min(bin_nelems, fixture_nelems) elements to handle
 * cases like text features where C truncates to real tokens.
 * Returns max abs diff, or -1 on skip.
 */
static float compare_bin_vs_fixture(const char *label,
				    const char *bin_path,
				    const char *fixture_path,
				    const char *tensor_name,
				    float atol)
{
	float *bin_data, *fix_data;
	int bin_n, fix_n, cmp_n;
	float maxd;

	bin_data = load_bin_file(bin_path, &bin_n);
	if (!bin_data) {
		printf("  %-30s SKIP (no bin dump)\n", label);
		return -1.0f;
	}

	fix_data = load_fixture_tensor(fixture_path, tensor_name,
				       NULL, NULL, &fix_n);
	if (!fix_data) {
		printf("  %-30s SKIP (no fixture)\n", label);
		free(bin_data);
		return -1.0f;
	}

	cmp_n = bin_n < fix_n ? bin_n : fix_n;
	if (bin_n != fix_n) {
		printf("  %-30s (comparing %d of C=%d/Py=%d)\n",
		       label, cmp_n, bin_n, fix_n);
	}

	maxd = compare_tensors(label, bin_data, fix_data, cmp_n, atol);

	free(bin_data);
	free(fix_data);
	return maxd;
}

/* ── Test: input normalization ─────────────────────────────────────── */

static void test_input_normalization(void)
{
	float *py_norm = NULL;
	int py_ndims, py_dims[SAM3_MAX_DIMS], py_nelems;

	printf("test_input_normalization:\n");

	py_norm = load_fixture_tensor(
		FIXTURE_DIR "/00_input/tensors.safetensors",
		"image", &py_ndims, py_dims, &py_nelems);
	ASSERT(py_norm != NULL);
	if (!py_norm)
		return;

	/* Fixture shape: [1, 3, 1008, 1008] */
	ASSERT_EQ(py_ndims, 4);
	ASSERT_EQ(py_dims[0], 1);
	ASSERT_EQ(py_dims[1], 3);
	ASSERT_EQ(py_dims[2], 1008);
	ASSERT_EQ(py_dims[3], 1008);

	/* Verify fixture values are in expected range */
	int in_range = 1;
	for (int i = 0; i < py_nelems && in_range; i++) {
		if (py_norm[i] < -1.001f || py_norm[i] > 1.001f)
			in_range = 0;
	}
	ASSERT(in_range);
	printf("  fixture values in [-1, 1]: yes\n");

	/* Test the C normalize function with known values */
	{
		uint8_t test_pixel[3] = {0, 127, 255};
		float test_out[3];
		sam3_normalize_rgb_chw(test_pixel, test_out, 1, 1);

		ASSERT_NEAR(test_out[0], -1.0f, 1e-5f);
		ASSERT_NEAR(test_out[1], 127.0f / 127.5f - 1.0f, 1e-5f);
		ASSERT_NEAR(test_out[2], 255.0f / 127.5f - 1.0f, 1e-5f);
		printf("  C normalize formula: correct\n");
	}

	free(py_norm);
}

/* ── Test: end-to-end with fixture input ───────────────────────────── */

static void test_end_to_end_fixture_input(void)
{
	struct sam3_processor proc;
	float *py_image = NULL;
	float *py_masks = NULL;
	int img_ndims, img_dims[SAM3_MAX_DIMS], img_nelems;
	int msk_ndims, msk_dims[SAM3_MAX_DIMS], msk_nelems;
	struct sam3_tensor *image;
	struct sam3_result result;
	struct sam3_prompt prompts[2];
	enum sam3_error err;
	int c_dims[3];

	printf("\ntest_end_to_end_fixture_input:\n");
	memset(&result, 0, sizeof(result));
	memset(&proc, 0, sizeof(proc));

	/* Load fixture normalized image [1, 3, 1008, 1008] */
	py_image = load_fixture_tensor(
		FIXTURE_DIR "/00_input/tensors.safetensors",
		"image", &img_ndims, img_dims, &img_nelems);
	ASSERT(py_image != NULL);
	if (!py_image)
		return;

	/* Load fixture masks [1, 200, 288, 288] */
	py_masks = load_fixture_tensor(
		FIXTURE_DIR "/10_final/tensors.safetensors",
		"pred_masks", &msk_ndims, msk_dims, &msk_nelems);
	ASSERT(py_masks != NULL);
	if (!py_masks)
		goto cleanup;

	ASSERT_EQ(msk_ndims, 4);
	ASSERT_EQ(msk_dims[0], 1);

	/* Open weight file and initialize processor */
	struct sam3_weight_file wf;
	memset(&wf, 0, sizeof(wf));
	err = sam3_weight_open(&wf, MODEL_PATH);
	ASSERT_EQ(err, SAM3_OK);
	if (err != SAM3_OK)
		goto cleanup;

	err = sam3_processor_init(&proc);
	ASSERT_EQ(err, SAM3_OK);
	if (err != SAM3_OK) {
		sam3_weight_close(&wf);
		goto cleanup;
	}

	err = sam3_processor_load(&proc, &wf,
				  SAM3_SOURCE_DIR "/models/bpe_simple_vocab_16e6.txt.gz");
	ASSERT_EQ(err, SAM3_OK);
	if (err != SAM3_OK) {
		sam3_weight_close(&wf);
		goto cleanup;
	}

	/* Inject fixture's normalized image directly */
	sam3_arena_reset(&proc.scratch_arena);
	c_dims[0] = 3;
	c_dims[1] = 1008;
	c_dims[2] = 1008;
	image = gh_alloc_tensor(&proc.scratch_arena, SAM3_DTYPE_F32,
				3, c_dims);
	ASSERT(image != NULL);
	if (!image)
		goto cleanup;

	memcpy(image->data, py_image,
	       (size_t)3 * 1008 * 1008 * sizeof(float));

	/* Encode image */
	err = sam3_image_model_encode(&proc.model, proc.backend, image,
				      &proc.scratch_arena,
				      &proc.model_arena);
	ASSERT_EQ(err, SAM3_OK);
	if (err != SAM3_OK)
		goto cleanup;

	proc.image_loaded = 1;

	/* ── Compare intermediate cached features ──────────────── */
	printf("\n  Intermediate stage comparison:\n");

	if (proc.model.cached_feat_4x) {
		compare_nchw_fixture(
			"neck scale_4x",
			proc.model.cached_feat_4x,
			FIXTURE_DIR "/02_neck/scale_4x.safetensors",
			"features");
	}

	if (proc.model.cached_feat_s0) {
		compare_nchw_fixture(
			"neck scale_2x",
			proc.model.cached_feat_s0,
			FIXTURE_DIR "/02_neck/scale_2x.safetensors",
			"features");
	}

	if (proc.model.cached_feat_s1) {
		compare_nchw_fixture(
			"neck scale_1x",
			proc.model.cached_feat_s1,
			FIXTURE_DIR "/02_neck/scale_1x.safetensors",
			"features");
	}

	/* ── Run segmentation ──────────────────────────────────── */
	prompts[0].type = SAM3_PROMPT_POINT;
	prompts[0].point.x = 500.0f;
	prompts[0].point.y = 400.0f;
	prompts[0].point.label = 1;

	prompts[1].type = SAM3_PROMPT_TEXT;
	prompts[1].text = "cat";

	err = sam3_processor_segment(&proc, prompts, 2, &result);
	ASSERT_EQ(err, SAM3_OK);
	if (err != SAM3_OK)
		goto cleanup;

	/* ── Compare debug dumps vs fixtures ───────────────────── */
	/*
	 * Stage 03 (pos encoding) is skipped: layout mismatch
	 * (C is HWC [72,72,256], Python is NCHW [1,256,72,72]).
	 * Already verified EXACT (max 6e-7) via manual flat check.
	 */
	printf("\n  Debug dump stage comparison:\n");

	/* 04 Text features — C truncated to real tokens */
	compare_bin_vs_fixture(
		"text features (04)",
		"/tmp/dbg_text_features.bin",
		FIXTURE_DIR "/04_text_encoder/output.safetensors",
		"language_features", 0.001f);

	/* 06 Encoder fusion layers L0-L5 */
	{
		char bin_path[256], fix_path[256];
		char label[64];
		for (int li = 0; li < 6; li++) {
			snprintf(bin_path, sizeof(bin_path),
				 "/tmp/dbg_enc_layer_%02d.bin", li);
			snprintf(fix_path, sizeof(fix_path),
				 FIXTURE_DIR
				 "/06_encoder_fusion/layer_%02d.safetensors",
				 li);
			snprintf(label, sizeof(label),
				 "enc layer %d (06)", li);
			compare_bin_vs_fixture(label, bin_path, fix_path,
					       "output", 15.0f);
		}
	}

	/* 09 Seg head — pixel decoder + instance projection */
	compare_bin_vs_fixture(
		"pixel decoder (09)",
		"/tmp/dbg_pixel_embed.bin",
		FIXTURE_DIR "/09_seg_head/pixel_decoder.safetensors",
		"pixel_features", 5.0f);

	compare_bin_vs_fixture(
		"instance proj (09)",
		"/tmp/dbg_inst.bin",
		FIXTURE_DIR "/09_seg_head/instance_proj.safetensors",
		"instance_features", 5.0f);

	/* ── Compare final masks ───────────────────────────────── */
	printf("\n  Final output comparison:\n");

	ASSERT_EQ(result.n_masks, msk_dims[1]);
	ASSERT_EQ(result.mask_height, msk_dims[2]);
	ASSERT_EQ(result.mask_width, msk_dims[3]);

	{
		int n = result.n_masks * result.mask_height *
			result.mask_width;
		float maxd = compare_tensors("pred_masks",
					     result.masks, py_masks,
					     n, 1.0f);

		/* Verify outputs are finite */
		int any_nan = 0;
		for (int i = 0; i < n && !any_nan; i++) {
			if (result.masks[i] != result.masks[i])
				any_nan = 1;
		}
		ASSERT(!any_nan);

		/* Report quality level */
		if (maxd < 0.01f)
			printf("  quality: EXACT\n");
		else if (maxd < 1.0f)
			printf("  quality: GOOD\n");
		else if (maxd < 10.0f)
			printf("  quality: FAIR (max=%.2f)\n",
			       (double)maxd);
		else
			printf("  quality: DIVERGED (max=%.2f) - "
			       "check intermediate stages\n",
			       (double)maxd);
	}

	/* Logit statistics */
	{
		int n = result.n_masks * result.mask_height *
			result.mask_width;
		int n_pos = 0, n_neg = 0;
		float vmin = result.masks[0], vmax = result.masks[0];

		for (int i = 0; i < n; i++) {
			if (result.masks[i] > 0.0f) n_pos++;
			if (result.masks[i] < 0.0f) n_neg++;
			if (result.masks[i] < vmin) vmin = result.masks[i];
			if (result.masks[i] > vmax) vmax = result.masks[i];
		}
		printf("  C logits: min=%.2f max=%.2f pos=%d neg=%d\n",
		       (double)vmin, (double)vmax, n_pos, n_neg);
	}

	/* Fixture logit statistics for comparison */
	{
		int n_pos = 0, n_neg = 0;
		float vmin = py_masks[0], vmax = py_masks[0];

		for (int i = 0; i < msk_nelems; i++) {
			if (py_masks[i] > 0.0f) n_pos++;
			if (py_masks[i] < 0.0f) n_neg++;
			if (py_masks[i] < vmin) vmin = py_masks[i];
			if (py_masks[i] > vmax) vmax = py_masks[i];
		}
		printf("  Py logits: min=%.2f max=%.2f pos=%d neg=%d\n",
		       (double)vmin, (double)vmax, n_pos, n_neg);
	}

cleanup:
	sam3_result_free(&result);
	sam3_processor_free(&proc);
	sam3_weight_close(&wf);
	free(py_image);
	free(py_masks);
}

/* ── Main ──────────────────────────────────────────────────────────── */

int main(void)
{
	if (!fixtures_available()) {
		printf("SKIP: fixtures not found at %s\n", FIXTURE_DIR);
		printf("Run: python3 tools/gen_fixtures.py\n");
		printf("0 tests, 0 failures\n");
		return 0;
	}

	test_input_normalization();

	if (model_available()) {
		test_end_to_end_fixture_input();
	} else {
		printf("SKIP: model not found at %s\n", MODEL_PATH);
		printf("  (skipping end-to-end test)\n");
	}

	TEST_REPORT();
}
