//! Raw FFI bindings to libsam3.
//!
//! This crate exposes the unmodified C API of libsam3 generated by
//! [`bindgen`]. For a safe, idiomatic wrapper, see the [`sam3`] crate.

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(deref_nullptr)]
#![allow(clippy::missing_safety_doc)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
